version: '3.9'
services:
  app:
    image: golang:1.18
    volumes:
      - ./:/var/www/otp/
    working_dir: /var/www/otp/
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    depends_on:
      - redis
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
